package br.com.maboo.tubarao.dados;

import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import br.com.maboo.tubarao.R;

public class DadosBitmap {

	private Resources res;

	public DadosBitmap(Resources res) {
		this.res = res;
	}

	/**
	 * Lista de sprites do tubarao normal
	 * 
	 * @return
	 */
	public Bitmap[] getImgTubNormal() {

		Bitmap[] bs_tubarao = new Bitmap[] {
				BitmapFactory.decodeStream(res
						.openRawResource(R.drawable.tub125x115_right)),
				BitmapFactory.decodeStream(res
						.openRawResource(R.drawable.tub125x115_left)) };
		return bs_tubarao;
	}

	/**
	 * Lista de sprites dos objetos
	 * 
	 * @return
	 */
	public Bitmap getImgObjetos(int indice) {

		switch (indice) {
		case PNEU:
			return BitmapFactory.decodeStream(res
					.openRawResource(R.drawable.obj_pneu46x42));

		case GARRAFA:
			return BitmapFactory.decodeStream(res
					.openRawResource(R.drawable.obj_garrafa16x42));

		case LATA:
			return BitmapFactory.decodeStream(res
					.openRawResource(R.drawable.obj_lata42x38));

		case BARRIL:
			return BitmapFactory.decodeStream(res
					.openRawResource(R.drawable.obj_lata42x38));

		}
		// no caso de erro, retorna a imagem da lata
		return BitmapFactory.decodeStream(res
				.openRawResource(R.drawable.obj_lata42x38));
	}

	/**
	 * 0: pneu | 1: garrafa | 2: lata | 3: barril
	 */
	private final static int PNEU = 0;
	private final static int GARRAFA = 1;
	private final static int LATA = 2;
	private final static int BARRIL = 3;

	public static final int[][] TIPO_OBJETOS_POR_NIVEL = {
			{ PNEU, GARRAFA, LATA },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL },
			{ PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, BARRIL, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					BARRIL, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, BARRIL, BARRIL, PNEU, BARRIL, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, BARRIL, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, BARRIL, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, BARRIL, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, BARRIL, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, BARRIL, GARRAFA, LATA, BARRIL,
					PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU,
					GARRAFA, LATA, PNEU, GARRAFA, BARRIL, BARRIL, PNEU,
					GARRAFA, LATA, BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA,
					LATA, BARRIL, PNEU, GARRAFA, LATA, BARRIL, PNEU, GARRAFA,
					LATA, PNEU, GARRAFA, BARRIL, BARRIL, PNEU, GARRAFA, LATA,
					BARRIL, PNEU, GARRAFA, LATA, PNEU, GARRAFA, LATA, BARRIL } };

	/**
	 * O peso dos objetos influencia na queda
	 * 
	 * 0: pneu | 1: garrafa | 2: lata | 3: barril
	 * 
	 */
	public static final int[] PESO_OBJETOS = { 3, 1, 1, 4 };

	/**
	 * Pontuação que cada objeto pode fornecer
	 * 
	 * 
	 * 0: pneu | 1: garrafa | 2: lata | 3: barril
	 * 
	 */
	public static final int[] PONTUACAO_OBJETOS = { 3, 1, 1, 5 };

}
